/**
 * #115 — `opa_get_rig_counts` read four keys the API has never sent.
 *
 * The formatter read `oil`, `gas`, `total` and `date`. Live
 * `GET /v1/rig-counts/latest` (api.oilpriceapi.com, verified 2026-09-13 with
 * the enterprise smoke key) answers:
 *
 *   {"status":"success","data":{
 *     "code":"US_RIG_COUNT","region":"United States","count":588,
 *     "currency":"COUNT","unit":"rigs","source":"market_reporting",
 *     "created_at":"2026-08-28T18:31:33.015Z",
 *     "collected_at":"2026-08-28T18:31:33.015Z",
 *     "observed_at":"2026-08-28T12:00:00.000Z",
 *     "source_date":"2026-08-28",
 *     "formatted_date":"2026-08-28 12:00:00 UTC"}}
 *
 * None of `oil`/`gas`/`total`/`date` exist in that envelope, so every line of
 * the answer was rendered from an absent field. #110 stopped that printing the
 * literal `undefined`, which means the tool now reports "not reported" four
 * times on a call where the API returned a perfectly good 588 — a confident
 * "we have no rig count" generated by our own client.
 *
 * The assertions below are on the RENDERED text an agent receives, driven
 * through the real registered handler with a stubbed `fetch`.
 */
import { describe, it, expect, vi, afterEach } from "vitest";
import { createSandboxServer } from "../index.js";

type ToolResult = {
  content: Array<{ type: string; text: string }>;
  isError?: boolean;
};

type Handler = (
  args: Record<string, unknown>,
  extra: Record<string, unknown>,
) => Promise<ToolResult>;

const server = createSandboxServer();
const tools = (
  server as unknown as {
    _registeredTools: Record<string, { handler: Handler }>;
  }
)._registeredTools;

/** Verbatim live payload, api.oilpriceapi.com/v1/rig-counts/latest, 2026-09-13. */
const LIVE_LATEST = {
  status: "success",
  data: {
    code: "US_RIG_COUNT",
    region: "United States",
    count: 588,
    currency: "COUNT",
    unit: "rigs",
    source: "market_reporting",
    created_at: "2026-08-28T18:31:33.015Z",
    collected_at: "2026-08-28T18:31:33.015Z",
    observed_at: "2026-08-28T12:00:00.000Z",
    source_date: "2026-08-28",
    formatted_date: "2026-08-28 12:00:00 UTC",
  },
};

function stubJson(body: unknown) {
  const fetchSpy = vi.fn().mockResolvedValue({
    ok: true,
    status: 200,
    statusText: "OK",
    headers: { get: () => null },
    json: async () => body,
    text: async () => JSON.stringify(body),
  });
  vi.stubGlobal("fetch", fetchSpy);
  return fetchSpy;
}

function textOf(result: ToolResult): string {
  return result.content.map((c) => c.text).join("\n");
}

afterEach(() => {
  vi.unstubAllEnvs();
  vi.unstubAllGlobals();
});

describe("#115 opa_get_rig_counts reads the fields the API actually sends", () => {
  it("renders the live count, region and observation date", async () => {
    vi.stubEnv("OILPRICEAPI_KEY", "test-key-123");
    stubJson(LIVE_LATEST);

    const result = await tools.opa_get_rig_counts.handler({}, {});
    const text = textOf(result);

    expect(result.isError).not.toBe(true);
    // The number the API returned must reach the agent.
    expect(text).toContain("588");
    expect(text).toContain("United States");
    expect(text).toContain("2026-08-28");
  });

  it("does not report an absent split as the whole answer", async () => {
    vi.stubEnv("OILPRICEAPI_KEY", "test-key-123");
    stubJson(LIVE_LATEST);

    const text = textOf(await tools.opa_get_rig_counts.handler({}, {}));

    // /v1/rig-counts carries no oil/gas split. Naming one and then reporting
    // it absent tells the agent we tried and failed to get data we never had.
    expect(text).not.toMatch(/Oil Rigs/i);
    expect(text).not.toMatch(/Gas Rigs/i);
    // And on a fully successful call nothing should be missing at all.
    expect(text.toLowerCase()).not.toContain("not reported");
  });

  it("never renders a literal undefined, whatever the API omits", async () => {
    vi.stubEnv("OILPRICEAPI_KEY", "test-key-123");
    // Degenerate envelope: success, but the record is stripped to nothing.
    stubJson({ status: "success", data: { code: "US_RIG_COUNT" } });

    const text = textOf(await tools.opa_get_rig_counts.handler({}, {}));

    expect(text).not.toContain("undefined");
    expect(text).not.toContain("NaN");
    expect(text).not.toContain("Invalid Date");
    // Absence must be stated, not silently rendered as a value.
    expect(text.toLowerCase()).toContain("not reported");
  });

  it("advertises only what /v1/rig-counts can answer", async () => {
    const definition = (
      server as unknown as {
        _registeredTools: Record<string, { description?: string }>;
      }
    )._registeredTools.opa_get_rig_counts;

    // The description is what an agent reads before deciding to call. It
    // promised oil rigs, gas rigs, a total and a week-over-week change; the
    // endpoint carries one count and no deltas.
    expect(definition.description ?? "").not.toMatch(/gas rigs/i);
    expect(definition.description ?? "").not.toMatch(/week-over-week/i);
  });
});
